### ISSUE TITLE
Implementing /:optional?

### ISSUE THREAD

**Issue by Fenny** [ucarion/urlpath#1] opened 2020-04-21 17:13 UTC
Hi @ucarion,

Your lib is awesome, we would love to use this in our web framework [Fiber](https://github.com/gofiber/fiber) and give you credits ofcourse.

I did some benchmarks versus pre-compiled regex and the results speak for themself:
```
BenchmarkRegexp-4        1634472               722 ns/op             304 B/op          3 allocs/op
BenchmarkUrlpath-4       6861980               185 ns/op             336 B/op          2 allocs/op
```

I'm wondering if we could work together to add one more feature to this package.
The so called optional param that is widely used in node frameworks: `/:optional?`

```go
/api/user/:optional?
// will match
/api/user
/api/user/john
```

Is this something you would be interested in working on together?

Thanks, Fenny!

**Comment by ucarion** [comment] 2020-04-21 21:50
Hi -- just so I understand, what's the benefit of an optional field, as opposed to using two paths? In other words, why not attempt to match against both `/api/user/:user` and `/api/user`?

Your benchmark does remind me that I should add benchmarks, to make sure any modifications to this library don't cause performance regressions. Though it's not an explicit goal, performance in urlpath is nice to have. :)

Regarding credit: urlpath is licensed under MIT. Please feel free to do anything that MIT allows you to do. :)

**Comment by Fenny** [comment] 2020-04-21 23:57
Thanks for your reply @ucarion, that's very kind of you!

The `/:optional` is widely used in the `expressjs` framework.
Mostly used to set default values, build queries or simple extra tasks / params that optional.

```js
app.Get("/articles/:year?/:month?/:day?", handler)
```

**Comment by ucarion** [comment] 2020-04-22 00:23
Would it ever make sense for optional parameters to be followed by required ones? In other words, would this be valid?

```
/foo/:bar?/:baz
```

If it's not valid to have optional followed by required -- in other words, all optional parts have to go at the end -- then this is starting to sound a lot like `Trailing`? Could you implement this on top of `urlpath` by instead of doing:

```
/foo/:bar?/:baz?
```

Doing:

```
/foo/*
```

And then re-running urlpath on the resulting `Trailing`, against:

```
/:baz/:bar
```

But this time, treating it as ok if the rest doesn't match?

In general, I'm a little worried about how well-defined the proposal here is. The exact semantics aren't super clear to me.

**Comment by Fenny** [comment] 2020-04-22 01:36
Everything before the `?` and after until a slash will become optional.

```js
/foo/:bar?/:baz

-> /foo/john
{ bar: undefined, baz: 'doe' }

-> /foo/john/doe
{ bar: 'john',    baz: 'doe' }
```

It wouldn't make much sense to use this infront of a parameter.
Same goes with `/foo/*/:baz`

An `/:optional?` is documented to be placed after `/:params`, just like wildcards.
The main difference compared to a `*` is that you have param name references.

```js
/articles/:year?/:month?/:day?

year = params["year"]  || 2020
year = params["month"] || 04
year = params["day"]   || 22
```

Your solution could work, but this means we have to run it twice which is something we would like to avoid.
Let me know what you think, thanks for taking the time to discuss this :-)

**Comment by ucarion** [comment] 2020-04-22 02:01
Just to be clear, `*` is allowed in the middle of a path. This is documented in the README:

> A "trailing" segment, *. This is only treated specially when it's the last segment -- otherwise, it's just a usual exact-match segment. Any leftover data in the input, after all previous segments were satisfied, goes into Trailing in the outputted Match.

With regards to:

> Your solution could work, but this means we have to run it twice which is something we would like to avoid. Let me know what you think, thanks for taking the time to discuss this :-)

I think if we're going to be adding something to this library that adds some weird caveats -- and I think you'd agree that there are a few weird corner-cases that optional segments would introduce -- then we need a stronger argument than "we'd prefer not to call Match twice". I hope that seems like a reasonable position to you.

I think we either need to iron out the exact semantics of optional parameters, and identify all of its weird corner-cases, or we should defer on adding this feature.

> PS: What do you think about adding a possibility to use a - dash?

I'm not sure we can add that feature in a backwards-compatible way, and I'm also not sure that it needs to be implemented in urlpath. Why not build this on top of urlpath?

**Comment by ucarion** [comment] 2020-04-23 01:47
For housekeeping purposes, I am going to close this ticket in 24 hours in the absence of any response.

**Comment by renanbastos93** [comment] 2020-04-23 01:59
Please, don't close it.

Even so, I believe that to use parameter optional just in the end path.
However, I need help to improve the method match to respecting the rule of parameter optional.

Can you help us?

---

> PS: What do you think about adding a possibility to use a - dash?
Here, I don't agree because of can cheat path when using in patter rest I can define my entity using `-`

According to below system will trick the URL path
```
route: /api/my-app
route2: /api/:a-:b

path: /api/my-app 
```

**Comment by ucarion** [comment] 2020-04-23 16:06
Sorry, I'm not sure I understand you, @renanbastos93 -- what is it you'd like help on?

I also don't understand what you're trying to say regarding `-`.

**Comment by renanbastos93** [comment] 2020-04-24 14:07
> Sorry, I'm not sure I understand you, @renanbastos93 -- what is it you'd like help on?
> 
> I also don't understand what you're trying to say regarding `-`.

I am so sorry, my English is not so good. I will try to explain it again.

**Comment by ucarion** [comment] 2020-04-24 23:53
No worries, @renanbastos93 -- when can I expect a reply?

**Comment by renanbastos93** [comment] 2020-04-25 03:32
> No worries, @renanbastos93 -- when can I expect a reply?

Well, first I am so sorry my English not so good.

I believe that this feature will improve and aggregate your module.

So I wish to help your module implementing a feature to parameter optional according to propose. But I'm not getting the why my approach doesn't work.

Do you understand me?

**Comment by ucarion** [comment] 2020-04-25 18:02
I think I do understand you -- and I am willing to give you some guidance implementing all of this. But I can't help you if you don't specify the problem a bit better.

However, right now I don't think the proposed feature is well-defined enough to be integrated into this module. It's a bit underspecified. So maybe forking this module, or just copy-pasting it, is a better option for now.

Is https://github.com/renanbastos93/urlpath/commit/2b7363a4a3a77d0836b781e25d2e9976854a89f5 the code you'd like to me to take a look at? If so: my question to you is: what do you want to have happen when someone does:

```
/:foo/bar/:baz?/*
```

And then you get an input like:

```
/xxx/bar/yyy
```

Is `yyy` going to correspond to `:baz?`, and `Trailing` is empty? Or should we consider `:baz?` to have been left out, and `Trailing `is `/yyy`?

I can't help you write the code until I understand what the code is meant to do. And it's corner-cases like these that I don't think anyone has thought through yet that prevent me from understanding what the code ought to do.

**Comment by ucarion** [comment] 2020-04-25 18:04
I'm going to close this ticket now. That doesn't mean I'm not gonna help you out, @renanbastos93. But it does mean I'm probably not going to accept the proposed feature into `urlpath`.

I can re-open this ticket, and reconsider this proposed feature, if someone can provide more concrete examples of the corner-cases involved in optional parameters interacting with each other, and with optional parameters interacting with `*`.

**Closed by ucarion** 2020-04-25 18:04 UTC

**Comment by renanbastos93** [comment] 2020-04-27 04:41
@ucarion

Okay, I will be planning some examples later we talk again.
But about this case `/:foo/bar/:baz?/*`  I wouldn't use a wildcard. Always the last param should be optional or wildcard never both.

thank you so much for you helping

**Comment by ucarion** [comment] 2020-04-27 22:44
The problem isn't "it's not a good idea". It's "what will happen".

**Comment by renanbastos93** [comment] 2020-05-01 19:35
Man, thanks a lot to help me.

Well, I am so sorry for later
Can we talk by email or some social network?

I have two problems in my algorithm now, I already accept the parameter optional, it doesn't match in these examples

```bash
/api/v1/const # don't accept slash in prefix
/api/v1/const/ # don't accept slash in the suffix
```

Regarding social networking, I have Telegram, Linkedin, etc...
All contact to me using @renanbastos93

**Comment by ucarion** [comment] 2020-05-04 16:13
Would you mind if we keep discussing this out in the open here? That way, the results are possible to Google-search and for others to find.

That said: if there's anything you'd prefer to email me directly about -- my email is: ulyssecarion@gmail.com

**Comment by renanbastos93** [comment] 2020-05-04 17:34
Hello

No worries, I improved the code and I did have a helped to improve it. So I created a new repo according to the description on readme  [fastpath](https://github.com/renanbastos93/fastpath). We had some changes in the logic to respect our needs. Now we’re going to implement [Fiber](https://github.com/gofiber/fiber) and yet we’ve managed to improve performance.

thanks a lot for helping us
